platform :ios, '9.0'

target 'Todoey' do

  use_frameworks!

  # Pods for Todoey

  pod 'RealmSwift'
  pod 'SwipeCellKit', :git => 'https://github.com/SwipeCellKit/SwipeCellKit.git', :branch => 'swift_4.2'

end
