# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FindFlower' do
  
  use_frameworks!
  
  # Pods for FindFlower

  pod 'Alamofire', '~> 4.4'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SDWebImage', '~> 5.0'

end
